/*
 * Copyright 2014-2018 Neueda Ltd.
 * 
 * Generated 08:18:20 18/04/19
 */
#ifndef OPTIQ_PACKETS_H
#define OPTIQ_PACKETS_H

/* #include "optiqMessageHeaderPacket.h" */
#include "optiqGroupSizeEncodingPacket.h"
#include "optiqMessageHeaderPacket.h"
#include "optiqGroupSizeEncoding16Packet.h"
#include "optiqNewOrderPacket.h"
#include "optiqAckPacket.h"
#include "optiqFillPacket.h"
#include "optiqKillPacket.h"
#include "optiqCancelReplacePacket.h"
#include "optiqRejectPacket.h"
#include "optiqQuotesPacket.h"
#include "optiqQuoteAckPacket.h"
#include "optiqQuoteRequestPacket.h"
#include "optiqCancelRequestPacket.h"
#include "optiqMassCancelPacket.h"
#include "optiqMassCancelAckPacket.h"
#include "optiqOpenOrderRequestPacket.h"
#include "optiqOwnershipRequestAckPacket.h"
#include "optiqOwnershipRequestPacket.h"
#include "optiqTradeBustNotificationPacket.h"
#include "optiqCollarBreachConfirmationPacket.h"
#include "optiqPriceInputPacket.h"
#include "optiqLiquidityProviderCommandPacket.h"
#include "optiqAskForQuotePacket.h"
#include "optiqRequestForExecutionPacket.h"
#include "optiqRFQNotificationPacket.h"
#include "optiqRFQMatchingStatusPacket.h"
#include "optiqUserNotificationPacket.h"
#include "optiqDeclarationEntryPacket.h"
#include "optiqDeclarationEntryAckPacket.h"
#include "optiqDeclarationNoticePacket.h"
#include "optiqDeclarationCancelAndRefusalPacket.h"
#include "optiqFundPriceInputPacket.h"
#include "optiqFundPriceInputAckPacket.h"
#include "optiqDeclarationEntryRejectPacket.h"
#include "optiqInstrumentSynchronizationListPacket.h"
#include "optiqSynchronizationTimePacket.h"
#include "optiqLogonPacket.h"
#include "optiqLogonAckPacket.h"
#include "optiqLogonRejectPacket.h"
#include "optiqLogoutPacket.h"
#include "optiqHeartbeatPacket.h"
#include "optiqTestRequestPacket.h"
#include "optiqTechnicalRejectPacket.h"
#include "optiqNewOrderFreeTextSectionPacket.h"
#include "optiqNewOrderMiFIDShortcodesPacket.h"
#include "optiqNewOrderOptionalFieldsPacket.h"
#include "optiqNewOrderClearingFieldsPacket.h"
#include "optiqFillOptionalFieldsFillPacket.h"
#include "optiqFillStrategyFieldsPacket.h"
#include "optiqCancelReplaceFreeTextSectionPacket.h"
#include "optiqCancelReplaceOptionalFieldsPacket.h"
#include "optiqCancelReplaceClearingFieldsPacket.h"
#include "optiqRejectCollarFieldsPacket.h"
#include "optiqQuotesMiFIDShortcodesPacket.h"
#include "optiqQuotesClearingDatasetPacket.h"
#include "optiqQuotesQuotesRepPacket.h"
#include "optiqQuoteAckQuoteAcksPacket.h"
#include "optiqInstrumentSynchronizationListInstrumentSynchronizationSectionPacket.h"

#endif
