/*
 * Copyright 2014-2018 Neueda
 */
#ifndef SWX_CODEC_CONSTANTS_H
#define SWX_CODEC_CONSTANTS_H

#include <stdint.h>


namespace neueda
{

#define SWX_SEQUENCED_MESSAGE_TYPE 'S'
#define SWX_UNSEQUENCED_MESSAGE_TYPE 'U'
#define SWX_ENTER_ORDER_MESSAGE_TYPE 'O'
#define SWX_REPLACE_ORDER_MESSAGE_TYPE 'U'
#define SWX_CANCEL_ORDER_MESSAGE_TYPE 'X'
#define SWX_SYSTEM_EVENT_MESSAGE_TYPE 'S'
#define SWX_ACCEPTED_MESSAGE_TYPE 'A'
#define SWX_REPLACED_MESSAGE_TYPE 'U'
#define SWX_ORDER_PRIORITY_UPDATE_CHANGE_MESSAGE_TYPE 'T'
#define SWX_CANCELLED_MESSAGE_TYPE 'C'
#define SWX_EXECUTED_ORDER_MESSAGE_TYPE 'E'
#define SWX_BROKEN_TRADE_MESSAGE_TYPE 'B'
#define SWX_REJECTED_ORDER_MESSAGE_TYPE 'J'
#define SWX_DEBUG_MESSAGE_TYPE '+'
#define SWX_LOGIN_ACCEPTED_MESSAGE_TYPE 'A'
#define SWX_LOGIN_REJECTED_MESSAGE_TYPE 'J'
#define SWX_CLIENT_HEARTBEAT_MESSAGE_TYPE 'R'
#define SWX_SERVER_HEARTBEAT_MESSAGE_TYPE 'H'
#define SWX_END_OF_SESSION_MESSAGE_TYPE 'Z'
#define SWX_LOGIN_REQUEST_MESSAGE_TYPE 'L'
#define SWX_LOGOUT_REQUEST_MESSAGE_TYPE 'O'

#define SWX_ORDERSTATE_LIVE 'L'
#define SWX_ORDERSTATE_DEAD 'D'

#define SWX_BOOKTYPE_DISPLAYEDORDEREXECUTION 'C'
#define SWX_BOOKTYPE_SWISSATMIDORDEREXECUTION 'M'

#define SWX_NOSTROCROSSFLAG_TWOPRINCIPALORDERSFROMTHESAMELEGALENTITYMATCHED 'N'
#define SWX_NOSTROCROSSFLAG_BLANKFOROTHERMATCHEDEXECUTIONS ' '

#define SWX_REASON_BREACHOFPRETRADECONTROLLIMIT 'B'
#define SWX_REASON_CANCELLEDDUETOSELFMATCHPREVENTION 'C'
#define SWX_REASON_IMMEDIATE 'I'
#define SWX_REASON_THEORDERBOOKINSTRUMENTBOARDORMARKETISNOTTRADABLEORWITHOUTTRADINGACCESSDEFINED 'H'
#define SWX_REASON_ORDERHASBEENDELETEDDUETOUSERLOGOFF 'L'
#define SWX_REASON_SUPERVISORY 'S'
#define SWX_REASON_TIMEOUT 'T'
#define SWX_REASON_USERREQUESTEDTHEORDERTOBECANCELLED 'U'
#define SWX_REASON_FLOWCONTROLISACTIVEUSERHASEXCEEDEDTHEIRCAPACITY 'F'
#define SWX_REASON_INVALIDORDERPLACEMENT 'K'
#define SWX_REASON_INVALIDSECONDARYQUALITY 'N'
#define SWX_REASON_THEORDERISNOTALLOWEDATTHISTIME 'R'
#define SWX_REASON_INVALIDICEBERGORDER 'V'
#define SWX_REASON_UNKNOWNCONTACTSUPPORTFORFURTHERINFORMATION 'W'
#define SWX_REASON_INVALIDPRICE 'X'
#define SWX_REASON_INVALIDORDER 'Y'
#define SWX_REASON_INVALIDQUANTITYEXCEEDSMAXIMUMLIMIT 'Z'
#define SWX_REASON_SPONSOREDACCESSUNAVAILABLE 'a'
#define SWX_REASON_MARKETORDERSNOTALLOWEDFORPRM 'b'
#define SWX_REASON_RESTRICTEDSTOCK 'c'
#define SWX_REASON_MAXVALUE 'd'
#define SWX_REASON_MAXSIZE 'e'
#define SWX_REASON_PRICECOLLARCHECKAGGRESSIVE 'f'
#define SWX_REASON_PRICECOLLARCHECKPASSIVE 'g'
#define SWX_REASON_TOTALNUMBEROFORDERS 'h'
#define SWX_REASON_ORDERTOTRADERATIO 'i'
#define SWX_REASON_TOTALRISKVALUE 'j'
#define SWX_REASON_TOTALBUYRISKVALUE 'k'
#define SWX_REASON_TOTALSELLRISKVALUE 'l'
#define SWX_REASON_TOTALTRADEDVALUE 'm'
#define SWX_REASON_TOTALNETRISKVALUE 'n'
#define SWX_REASON_TOTALEXPOSURE 'o'
#define SWX_REASON_SPONSOREDACCESSKILLSWITCHINFORCE 'z'

#define SWX_TIMEINFORCE_IMMEDIATE 0
#define SWX_TIMEINFORCE_SESSIONORDEREXPIRESATCLOSE 99996
#define SWX_TIMEINFORCE_SESSIONORDEREXPIRESATTHEOPENING 99997
#define SWX_TIMEINFORCE_DAYORDEREXPIRESATENTEROFPOSTTRADING 99998

#define SWX_ORDERVERB_BUY 'B'
#define SWX_ORDERVERB_SELL 'S'

#define SWX_REJECTREASONCODE_NOTAUTHORIZEDINVALIDUSERNAMEORPASSWARD 'A'
#define SWX_REJECTREASONCODE_SESSIONNOTAVAILABLEORINVALID 'S'

#define SWX_LIQUIDITYFLAG_ADDEDFORTHEPASSIVEPRINCIPAL 'A'
#define SWX_LIQUIDITYFLAG_REMOVEDFORTHEAGGRESSOR 'R'
#define SWX_LIQUIDITYFLAG_UNCROSSFORAUCTIONEXECUTIONS 'A'

#define SWX_ORDERPLACEMENT_DISPLAYEDORDER 'C'
#define SWX_ORDERPLACEMENT_LIMITPLUSORDER 'F'
#define SWX_ORDERPLACEMENT_SWISSATMIDORDER 'M'
#define SWX_ORDERPLACEMENT_ICEBERGPLUSORDER 'P'
#define SWX_ORDERPLACEMENT_SWEEPSWISSATMIDORDER 'S'

#define SWX_EVENTCODE_STARTOFDAY 'S'
#define SWX_EVENTCODE_ENDOFDAY 'E'


} // namespace neueda

#endif /* SWX_CODEC_CONSTANTS_H */